on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target_type: [server, client]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Cache XMake
        uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - name: Configure and Build
        run: |
          xmake repo -u
          xmake c -a
          xmake f -a x64 -m release -p windows -v -y --target_type=${{ matrix.target_type }}
          xmake package -v -y

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.target_type }}-windows-x64-${{ github.sha }}
          path: |
            bin/dll
      
      - name: Upload PDB
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.target_type }}-windows-x64-PDB
          path: |
            bin/pdb

      - name: Upload SDK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.target_type }}-SDK
          path: |
            bin/sdk
