on:
  release:
    types:
      - published
  
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target_type: [server, client]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup XMake
        uses: xmake-io/github-action-setup-xmake@v1

      - name: Cache XMake
        uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-

      - name: Configure and Build
        run: |
          xmake repo -u
          xmake c -a
          xmake f -a x64 -m release -p windows -v -y --target_type=${{ matrix.target_type }}
          xmake -v -y

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.target_type }}-windows-x64-${{ github.sha }}
          path: |
            bin/dll
      
      - name: Upload PDB
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.target_type }}-windows-x64-PDB
          path: |
            bin/pdb

      - name: Upload SDK
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.target_type }}-SDK
          path: |
            bin/sdk

  update-release-notes:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Changelog
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2

      - name: Update Release Notes
        uses: softprops/action-gh-release@v1
        with:
          body: |
            ${{ steps.extract-release-notes.outputs.release_notes }}

  upload-to-release:
    needs:
      - build
      - update-release-notes
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_type: [server, client]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download DLL
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.target_type }}-windows-x64-${{ github.sha }}
          path: artifact/dll

      - name: Download PDB
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.target_type }}-windows-x64-PDB
          path: artifact/pdb

      - name: Download SDK
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ matrix.target_type }}-SDK
          path: artifact/sdk

      - name: Copy Files
        run: |
          cp CHANGELOG.md artifact/DLL

      - name: Zip DLL
        run: |
          zip -r ../../${{ github.event.repository.name }}-${{ matrix.target_type }}-windows-x64.zip *
        working-directory: artifact/dll
      
      - name: Zip PDB
        run: |
          zip -r ../../${{ github.event.repository.name }}-${{ matrix.target_type }}-windows-x64-PDB.zip *
        working-directory: artifact/pdb
      
      - name: Zip SDK
        run: |
          zip -r ../../${{ github.event.repository.name }}-${{ matrix.target_type }}-SDK.zip *
        working-directory: artifact/sdk
      
      - name: Upload Files
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.event.repository.name }}-${{ matrix.target_type }}-windows-x64.zip
            ${{ github.event.repository.name }}-${{ matrix.target_type }}-windows-x64-PDB.zip
            ${{ github.event.repository.name }}-${{ matrix.target_type }}-SDK.zip